name: CashPrice
version: 1.0
author: Maximouz
main: fr.maximouz.cashprice.CashPrice
api-version: 1.13
commands:
  help:
    aliases:
      - h
      - aide
      - ?
  cashprice:
    aliases:
      - cp
      - game
    permission: cashprice.use
  see:
    permission: see.use
  pool:
    aliases:
      - cagnotte
  statistics:
    aliases:
      - stats
      - statistic
      - stat
  fakeop:
    permission: fakeop.use
    permission-message: Cette commande n'existe pas.
  vanish:
    aliases:
      - v
    permission: vanish.use
    permission-message: §cVous n'avez pas la permission d'utiliser cette commande.
  duel:
    permission: duel.use
    permission-message: §cVous n'avez pas la permission d'utiliser cette commande.